% Create Synthetic Files

% © All rights reserved. 
% ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, 
% Interdisciplinary Laboratory of Performance-Integrate Design, 2016
% Parag Rastogi
% See the LICENSE.TXT file for more details.

function  OutputTable = WeatherFileParseEPWUSDOE(FileName)

% This script takes as input a path (character/string) to an EPW file
% downloaded from the EnergyPlus weather websites (climate.onebuilding.org
% or energyplus.net). The format is described in the EnergyPlus
% documentation, and is generally known as the EPW format.
% A sister script is also in this repository - WeatherFileParseMeteonorm .
% This is slightly different because it does not have the extra three
% columns (called UnknownVar in this script)

p = inputParser;
p.FunctionName = 'WeatherFileParseEPWUSDOE';

addRequired(p,'FileName', @(x) (ischar(x) || (iscell(x) ...
    && length(x)==1)))

% Warning ID generated by readtable when it has to change incompatible
% variable names
warnid= 'MATLAB:table:ModifiedVarnames';
warning('off',warnid)

parse(p,FileName)

% If input file name is a cell, convert to string.
if iscell(p.Results.FileName)
    FileName = char(p.Results.FileName);
else
    FileName = p.Results.FileName;
end

% Check if file input ends with 'EPW' extension
if ~strcmpi(FileName(end-3:end),'.epw')
    fprintf('Input File Name is not an EPW file. Please try again.\n');
    OutputTable = array2table(NaN*ones(8760,33));
    return
end

% Full names of the variables
% 6. Quality Flags - ignore
% 7. Dry bulb temperature
% 8. Dew point temperature
% 9. Relative Humidity
% 10. Atmospheric Pressure
% 11. Horizontal Extra-Terrestrial Radiation
% 12. Normal Extra-Terrestrial Radiation
% 13. High Infra-Red radiation
% 14. Global Horizontal Irradiation
% 15. Direct Normal Irradiation
% 16. Diffuse Horizontal Irradiation
% 17. Global Horizontal Illuminance
% 18. Direct Normal Illuminance
% 19. Diffuse Horizontal Illuminance
% 20. Zentih Luminance
% 21. Wind Direction
% 22. Wind Speed
% 23. Total Sky Cover
% 24. Opaque Sky Cover
% 25. Visibility
% 26. Ceiling Height
% 27. Present Weather Observation
% 28. Present Weather Codes
% 29. Precipitable Water
% 30. Aerosol Optical Depth
% 31. Snow Depth
% 32. Days since last snowfall

% Names for the variables, from standardised list based on DOE EPW format
VarNames = {'Year', 'Month', 'Day', 'Hour', 'Minute', 'QualFlags', ...
    'TDB', 'TDP', 'RH', 'ATMPR', 'ETRH', 'ETRN', 'HIR', 'GHI',...
    'DNI', 'DHI', 'GHE', 'DNE', 'DHE', 'ZL', 'WDR', 'WSPD', 'TSKY',...
    'OSKY', 'VIS', 'CHGT', 'PWO', 'PWC', 'PWT', 'AOPT', 'SDPT',...
    'SLAST', 'UnknownVar1', 'UnknownVar2', 'UnknownVar3'};
% Units for the variables, from standardised list based on DOE EPW format
VarUnits = {'','','','','','','C','C','%','Pa','Wh/m2','Wh/m2',...
    'Wh/m2','Wh/m2','Wh/m2','Wh/m2','lux','lux','lux','Cd/m2',...
    'degrees','m/s','dimless','dimless', 'km', 'm', 'dimless',...
    'dimless','mm','thousandths','cm','days','','',''};

OutputTable = readtable(FileName,...
    'FileType', 'text','HeaderLines',8,'Delimiter',',',...
    'ReadVariableNames',0);

% The last three columns of EPW files are not mentioned in the EPW user
% manual. The values in those columns are meaningless as well. They are
% ignored by this parser and all other functions and not included in the 
% output.

% Assign variable names and units to table
OutputTable.Properties.VariableNames = VarNames(1:size(OutputTable,2));
OutputTable.Properties.VariableUnits = VarUnits(1:size(OutputTable,2));

% Attach description for identification
OutputTable.Properties.Description = 'USDOE';

end
