SMY_Create({'GEN'}, ...
    'C:\Users\prastogi\Documents\allmycode\SyntheticWeather\m-data', ...
    'C:\Users\prastogi\Documents\WeatherData\SyntheticData', ...
    'sublabel', 50, 'scenario', 'rcp85', 'srcEPWfile', ...
    'C:\Users\prastogi\Documents\allmycode\SyntheticWeather\m-data\GEN\GEN_IWEC.epw')

SMY_Create({'GEN'}, ...
    'C:\Users\prastogi\Documents\allmycode\SyntheticWeather\m-data', ...
    'C:\Users\prastogi\Documents\WeatherData\SyntheticData', ...
    'sublabel', 50, 'scenario', 'rcp45', 'srcEPWfile', ...
    'C:\Users\prastogi\Documents\allmycode\SyntheticWeather\m-data\GEN\GEN_IWEC.epw')